# Generated by Django 5.2.8 on 2025-11-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('published_date', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('product_price', models.CharField(max_length=20)),
            ],
        ),
    ]
